name: automerge
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Require-reviewers
        uses: travelperk/label-requires-reviews-action@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          rules_yaml:
            dependencies: 0
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_LABELS: "dependencies"
          MERGE_REQUIRED_APPROVALS: 0
          MERGE_DELETE_BRANCH: true
          MERGE_RETRIES: 10
          # Our deployment runs take a long time to complete; check each 11 minutes
          MERGE_RETRY_SLEEP: 660000
