name: Automerge Pull Requests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - name: Wait for status checks
        uses: "WyriHaximus/github-action-wait-for-status@v1.8.0"
        with:
          ignoreActions: Automerge Pull Requests
          checkInterval: 333
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.15.6
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          MERGE_METHOD: "squash"
          MERGE_LABELS: ""
          MERGE_FORKS: false
          # We need a token from a maintainer who can merge even if not all requirements (e.g., reviews) are met
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN_COMMENT_ON_PR }}"
